version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t flask-app .
      - $(aws ecr get-login --no-include-email --region ap-south-1)
      - docker tag flask-app:latest 503561445201.dkr.ecr.ap-south-1.amazonaws.com/flask-app:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push 503561445201.dkr.ecr.ap-south-1.amazonaws.com/flask-app:latest
