version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t my-python-app .
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - docker tag my-python-app:latest <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/my-python-app:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/my-python-app:latest
