version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 503561445201.dkr.ecr.ap-south-1.amazonaws.com
      - echo "Building the Docker image..."
      - docker build -t flask-app . 
      - echo "Tag the image..."
      - docker tag flask-app:latest 503561445201.dkr.ecr.ap-south-1.amazonaws.com/flask-app:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push 503561445201.dkr.ecr.ap-south-1.amazonaws.com/flask-app:latest
      - echo "Running Docker Container..."
      - docker container run -d -p 80:80 flask-app
      
